language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer selfupdate
  - composer install

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

script: phpunit --coverage-text --configuration phpunit.xml.dist
