language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer selfupdate
  - composer install

script:
  - phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - $CODECLIMATE_REPO_TOKEN vendor/bin/test-reporter
